backend:
  name: git-gateway
  repo: your_name/repo_name

media_folder: "static/media"
public_folder: "/media"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/content/home.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}
          - {label: "Image Alt Text", name: "hero_alt", widget: "string"}
          - {label: "Body Content", name: "body", widget: "markdown"}
      - label: "About"
        name: "about"
        file: "src/content/about.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}
          - {label: "Image Alt Text", name: "hero_alt", widget: "string"}
          - {label: "Body Content", name: "body", widget: "markdown"}
      - label: "Services"
        name: "services"
        file: "src/content/services.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}
          - {label: "Image Alt Text", name: "hero_alt", widget: "string"}
          - {label: "Body Content", name: "body", widget: "markdown"}
      - label: "Contact"
        name: "contact"
        file: "src/content/contact.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}
          - {label: "Image Alt Text", name: "hero_alt", widget: "string"}
          - {label: "Body Content", name: "body", widget: "markdown"}